# Default server configuration
# TODO: define server blocks and routes for webserv.

server {
    listen 0.0.0.0:8080;
    server_name localhost;
    client_max_body_size 1048576;
    root ./www;

    location / {
        index index.html;
        allow_methods GET POST DELETE;
        autoindex on;
    }
}
