# Default server configuration
# TODO: define server blocks and routes for webserv.

server {
    listen 8080;
    server_name localhost;
    root ./www;

    location / {
        index index.html;
    }
}
